# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: Yzc4MjBhNDZlYzM5YjZlZWQ4MGYxNzk5MjBkMTVhZDhiNmExZGU3MmVlYTY4ZWY5ZmM5YTU0YzM5MGQ5MmQ2MGFjYWJlNmJjYmRlZjFhZGY3NDY2ZjJkYmFjMmE2NmVlOTJkODhhNGNkOThmNzU4ZTA3M2U5NjBhOTQ1NTJmMDM=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
